"""
File writer — dumps the in-memory file maps from the codegen agents onto
disk, generates README.md + manifest.json, and zips the whole project.

This is a deterministic node: no LLM, no I/O over the network. Anything
the LLM would be unreliable about (folder layout, README contents,
manifest schema) lives here as plain Python.

Reads:
  - state["architecture"]["project_name"]
  - state["frontend_code"]   — {filename: contents}
  - state["backend_code"]    — {filename: contents}
  - state["ai_code"]         — {filename: contents}; ai/ folder skipped when empty
  - state["config_code"]     — {filename: contents}

Writes:
  - output/<project_name>/{frontend,backend,ai?,config}/...
  - output/<project_name>/README.md
  - output/<project_name>/manifest.json
  - output/<project_name>.zip
  - state["output_dir"]      — absolute path to the project folder
  - state["zip_path"]         — absolute path to the zip artifact
"""

import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List

from core.state import AgentState


PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_ROOT = PROJECT_ROOT / "output"

# Characters we refuse to let into the project_name. The orchestrator is
# instructed to emit snake_case, but a stray "../" or absolute path would
# escape OUTPUT_ROOT, so we sanitize defensively.
_UNSAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_\-.]+")


def _sanitize_project_name(name: str) -> str:
    """Strip anything that could break filesystem placement; fall back to default."""
    cleaned = _UNSAFE_NAME_RE.sub("_", (name or "").strip()).strip("._")
    return cleaned or "generated_project"


def _write_file_map(target_dir: Path, file_map: Dict[str, str]) -> List[str]:
    """
    Dump {filename: contents} into target_dir. Filenames may include
    subpaths (e.g. "src/components/TodoList.jsx") — parent dirs are
    created as needed.

    Returns the list of files actually written, as paths relative to the
    project root (so they're directly usable in manifest.json).
    """
    written: List[str] = []
    if not file_map:
        return written

    target_dir.mkdir(parents=True, exist_ok=True)

    for filename, contents in file_map.items():
        # Reject absolute paths and any traversal attempts — file maps
        # come from the LLM and we can't trust them to stay inside the
        # subfolder we picked.
        rel = Path(filename)
        if rel.is_absolute() or ".." in rel.parts:
            continue

        dest = target_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)

        text = contents if isinstance(contents, str) else json.dumps(contents)
        dest.write_text(text, encoding="utf-8")

        # Relative-to-project-root path for manifest readability.
        written.append(str(dest.relative_to(target_dir.parent)))

    return written


def _render_readme(project_name: str, has_ai: bool) -> str:
    """Plain Markdown quickstart pinned to the ports the config_code uses."""
    ai_note = (
        "\nThis project includes a LangChain/Ollama AI layer under `ai/`. "
        "Make sure Ollama is running locally before starting the backend.\n"
        if has_ai
        else ""
    )
    return (
        f"# {project_name}\n"
        "\n"
        "Generated by the multi-agent code generation system.\n"
        f"{ai_note}"
        "\n"
        "## Ports\n"
        "\n"
        "- Frontend: http://localhost:3000\n"
        "- Backend:  http://localhost:8000\n"
        "\n"
        "## Run the frontend\n"
        "\n"
        "```bash\n"
        "cd frontend\n"
        "npm install\n"
        "npm run dev\n"
        "```\n"
        "\n"
        "## Run the backend\n"
        "\n"
        "```bash\n"
        "cd backend\n"
        "pip install -r requirements.txt\n"
        "uvicorn main:app --host 0.0.0.0 --port 8000\n"
        "```\n"
        "\n"
        "## Project layout\n"
        "\n"
        "- `frontend/` — React + Tailwind app\n"
        "- `backend/`  — FastAPI + SQLite service\n"
        + ("- `ai/`       — LangChain integration\n" if has_ai else "")
        + "- `config/`   — `docker-compose.yml`, `.env.example`, etc.\n"
    )


def _render_manifest(project_name: str, files: List[str]) -> str:
    """Stable JSON manifest — sorted file list, ISO-8601 UTC timestamp."""
    payload = {
        "project_name": project_name,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "files": sorted(files),
        "total_files": len(files),
    }
    return json.dumps(payload, indent=2) + "\n"


def file_writer(state: AgentState) -> AgentState:
    """Materialize the generated project on disk and zip it."""
    architecture = state["architecture"]
    project_name = _sanitize_project_name(architecture.get("project_name", ""))

    frontend_code = state.get("frontend_code", {}) or {}
    backend_code = state.get("backend_code", {}) or {}
    ai_code = state.get("ai_code", {}) or {}
    config_code = state.get("config_code", {}) or {}

    project_dir = OUTPUT_ROOT / project_name

    # Clean any prior run so stale files from a previous architecture (e.g.
    # a renamed component) don't linger in the output.
    if project_dir.exists():
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True, exist_ok=True)

    written: List[str] = []
    written.extend(_write_file_map(project_dir / "frontend", frontend_code))
    written.extend(_write_file_map(project_dir / "backend", backend_code))
    if ai_code:
        # Only create the ai/ folder when there's actually AI code — keeps
        # the layout honest for non-AI apps.
        written.extend(_write_file_map(project_dir / "ai", ai_code))
    written.extend(_write_file_map(project_dir / "config", config_code))

    readme_path = project_dir / "README.md"
    readme_path.write_text(
        _render_readme(project_name, has_ai=bool(ai_code)), encoding="utf-8"
    )
    written.append(str(readme_path.relative_to(OUTPUT_ROOT)))

    manifest_path = project_dir / "manifest.json"
    # Manifest lists every other written file but not itself — including
    # itself would force a second pass to keep total_files consistent.
    manifest_path.write_text(_render_manifest(project_name, written), encoding="utf-8")

    # shutil.make_archive appends ".zip" itself, so strip it from base_name.
    zip_base = OUTPUT_ROOT / project_name
    if zip_base.with_suffix(".zip").exists():
        zip_base.with_suffix(".zip").unlink()
    archive_path = shutil.make_archive(
        base_name=str(zip_base),
        format="zip",
        root_dir=str(OUTPUT_ROOT),
        base_dir=project_name,
    )

    state["output_dir"] = str(project_dir.resolve())
    state["zip_path"] = str(Path(archive_path).resolve())
    return state
